### ISSUE TITLE
Memory Leakage issue while playing Spotify-Web-SDK on Linux Machine

### ISSUE THREAD

**Issue by apanmehta** [spotify/web-playback-sdk#53] opened 2018-12-13 13:00 UTC
We are testing the Spotify Web SDK and what I found is there is memory leakage issue in Web SDK. It continuously consumes the memory without releasing it, until the web page is refreshed.
We want Spotify Web SDK to be running continuously on our system, which we are not able to do because system crashes after a certain amount of time. I have tested the same SDK on Chrome and Chromium on Linux-Ubuntu 18.04, but the issue is the same.

Steps to reproduce:
Open the Web SDK on any of the browser and check the memory usage, which continuously increases until system crashes.

Expected behavior : The Web SDK should release the memory consumed after certain amount of time or after each song, or while any playback control action takes place.

Actual behavior : Web SDK is continuously consuming the memory until system crashes.

**Comment by fafcrumb** [comment] 2019-01-19 08:33
Hi, this is a duplicate of #48 
Could you please close this?

**Closed** 2019-01-19 09:19 UTC
