### ISSUE TITLE
web Player is prioritizing spotify player play queue

### ISSUE THREAD

**Issue by humusdigital** [spotify/web-playback-sdk#103] opened 2020-01-22 04:33 UTC
Issue found on *20/02/2019*.

#### Steps to reproduce:
1. via js set a track into web-playback-sdk
2. The web player some times play a track from spotify play queue and not the correct track set via js.

**Comment by anker2000** [comment] 2020-01-22 08:22
Looks like a duplicate of #99

**Comment by joshubrown** [comment] 2020-01-28 15:05
We made some updates earlier this week that should resolve the problem with API-initiated playback. If you are still experiencing the issue then please let us know 🙂

**Closed by joshubrown** 2020-01-28 15:05 UTC
